// 102 Comprehensive English Dictionary Entries across 8 Categories and 3 Difficulties
export const DICTIONARY_WORDS = [
  // Everyday English (Easy & Medium)
  {
    id: "abundant",
    word: "Abundant",
    phonetic: "/əˈbʌn.dənt/",
    pos: "adjective",
    simpleDef: "Existing in large quantities; more than enough.",
    detailedDef: "Marked by great plenty or an ample supply of resources or goods.",
    example: "The orchard produced an abundant harvest of sweet apples this autumn.",
    synonyms: ["plentiful", "copious", "ample", "bountiful"],
    difficulty: "easy",
    category: "Everyday English",
    price: 20
  },
  {
    id: "curious",
    word: "Curious",
    phonetic: "/ˈkjʊə.ri.əs/",
    pos: "adjective",
    simpleDef: "Eager to know or learn something new.",
    detailedDef: "Desirous of investigating and acquiring information about unfamiliar subjects.",
    example: "The curious child examined the colorful seashells along the shoreline.",
    synonyms: ["inquisitive", "intrigued", "prying", "keen"],
    difficulty: "easy",
    category: "Everyday English",
    price: 20
  },
  {
    id: "diligent",
    word: "Diligent",
    phonetic: "/ˈdɪl.ɪ.dʒənt/",
    pos: "adjective",
    simpleDef: "Showing steady, earnest, and energetic effort.",
    detailedDef: "Characterized by persistent application and conscientious care in work or duty.",
    example: "Through diligent practice every evening, she mastered the classical violin.",
    synonyms: ["hardworking", "assiduous", "meticulous", "conscientious"],
    difficulty: "easy",
    category: "Everyday English",
    price: 25
  },
  {
    id: "genuine",
    word: "Genuine",
    phonetic: "/ˈdʒen.ju.ɪn/",
    pos: "adjective",
    simpleDef: "Truly what something is said to be; authentic.",
    detailedDef: "Free from pretense or deceit; possessing sincere and original character.",
    example: "He offered a genuine smile and apologized for the misunderstanding.",
    synonyms: ["authentic", "sincere", "real", "bona fide"],
    difficulty: "easy",
    category: "Everyday English",
    price: 20
  },
  {
    id: "harmony",
    word: "Harmony",
    phonetic: "/ˈhɑː.mə.ni/",
    pos: "noun",
    simpleDef: "Agreement, accord, or a pleasing combination of elements.",
    detailedDef: "A state of peaceful cooperation, or the pleasing arrangement of sound and visual parts.",
    example: "The diverse team members worked in complete harmony toward their shared goal.",
    synonyms: ["accord", "concord", "symmetry", "unity"],
    difficulty: "easy",
    category: "Everyday English",
    price: 20
  },
  {
    id: "lucid",
    word: "Lucid",
    phonetic: "/ˈluː.sɪd/",
    pos: "adjective",
    simpleDef: "Expressed clearly and easy to understand.",
    detailedDef: "Characterized by clear perception or presentation; intelligible and sane.",
    example: "The professor gave a lucid explanation of an otherwise complicated theorem.",
    synonyms: ["clear", "coherent", "transparent", "articulate"],
    difficulty: "medium",
    category: "Everyday English",
    price: 35
  },
  {
    id: "mundane",
    word: "Mundane",
    phonetic: "/mʌnˈdeɪn/",
    pos: "adjective",
    simpleDef: "Lacking interest or excitement; dull or routine.",
    detailedDef: "Relating to the ordinary world as contrasted with the exceptional or spiritual.",
    example: "He found tranquility in mundane chores like folding laundry and washing dishes.",
    synonyms: ["ordinary", "routine", "humdrum", "banal"],
    difficulty: "medium",
    category: "Everyday English",
    price: 35
  },
  {
    id: "pragmatic",
    word: "Pragmatic",
    phonetic: "/præɡˈmæt.ɪk/",
    pos: "adjective",
    simpleDef: "Dealing with things sensibly and realistically based on practical results.",
    detailedDef: "Guided by practical experience and actual outcomes rather than abstract ideals.",
    example: "They adopted a pragmatic strategy to resolve the budget deficit quickly.",
    synonyms: ["practical", "sensible", "down-to-earth", "utilitarian"],
    difficulty: "medium",
    category: "Everyday English",
    price: 40
  },
  {
    id: "tenacious",
    word: "Tenacious",
    phonetic: "/təˈneɪ.ʃəs/",
    pos: "adjective",
    simpleDef: "Holding firmly to a purpose; not giving up easily.",
    detailedDef: "Tending to adhere tightly and persistently despite formidable obstacles.",
    example: "Her tenacious pursuit of justice led to significant reform across the organization.",
    synonyms: ["persistent", "determined", "resolute", "dogged"],
    difficulty: "medium",
    category: "Everyday English",
    price: 45
  },
  {
    id: "ubiquitous",
    word: "Ubiquitous",
    phonetic: "/juːˈbɪk.wɪ.təs/",
    pos: "adjective",
    simpleDef: "Present, appearing, or found everywhere.",
    detailedDef: "Constantly encountered or existing in all places at the same time.",
    example: "Smartphones have become ubiquitous companions in modern urban life.",
    synonyms: ["omnipresent", "pervasive", "universal", "everywhere"],
    difficulty: "hard",
    category: "Everyday English",
    price: 60
  },
  {
    id: "ephemeral",
    word: "Ephemeral",
    phonetic: "/ɪˈfem.ər.əl/",
    pos: "adjective",
    simpleDef: "Lasting for a very short period of time.",
    detailedDef: "Brief and transient in existence; fleeting like morning dew or spring blossoms.",
    example: "The radiant colors of the sunset were beautiful yet ephemeral.",
    synonyms: ["fleeting", "transient", "momentary", "short-lived"],
    difficulty: "hard",
    category: "Everyday English",
    price: 65
  },
  {
    id: "fastidious",
    word: "Fastidious",
    phonetic: "/fæsˈtɪd.i.əs/",
    pos: "adjective",
    simpleDef: "Very attentive to accuracy and details; hard to please.",
    detailedDef: "Showing meticulous demand for exactitude, cleanliness, and delicate propriety.",
    example: "The watchmaker was fastidious about aligning each microscopic gear.",
    synonyms: ["meticulous", "painstaking", "scrupulous", "fussy"],
    difficulty: "hard",
    category: "Everyday English",
    price: 60
  },
  {
    id: "serendipity",
    word: "Serendipity",
    phonetic: "/ˌser.ənˈdɪp.ə.ti/",
    pos: "noun",
    simpleDef: "The occurrence of finding valuable things unexpectedly.",
    detailedDef: "The faculty of making fortunate discoveries by pure chance or happy accident.",
    example: "Finding her favorite out-of-print novel in a train station was pure serendipity.",
    synonyms: ["chance", "fluke", "fortune", "providence"],
    difficulty: "medium",
    category: "Everyday English",
    price: 45
  },

  // Emotions (Easy, Medium, Hard)
  {
    id: "empathy",
    word: "Empathy",
    phonetic: "/ˈem.pə.θi/",
    pos: "noun",
    simpleDef: "The ability to understand and share the feelings of another.",
    detailedDef: "Psychological capacity to vicariously experience the emotions and thoughts of another.",
    example: "Good counselors listen with deep empathy and never pass hasty judgment.",
    synonyms: ["compassion", "understanding", "sensitivity", "fellow feeling"],
    difficulty: "easy",
    category: "Emotions",
    price: 20
  },
  {
    id: "serene",
    word: "Serene",
    phonetic: "/səˈriːn/",
    pos: "adjective",
    simpleDef: "Calm, peaceful, and untroubled.",
    detailedDef: "Marked by complete tranquility and clear, undisturbed composure.",
    example: "The monk maintained a serene demeanor despite the bustling crowds around him.",
    synonyms: ["peaceful", "tranquil", "placid", "composed"],
    difficulty: "easy",
    category: "Emotions",
    price: 20
  },
  {
    id: "euphoria",
    word: "Euphoria",
    phonetic: "/juːˈfɔː.ri.ə/",
    pos: "noun",
    simpleDef: "A feeling or state of intense excitement and happiness.",
    detailedDef: "An overwhelming sense of wellbeing, elation, and boundless joy.",
    example: "The championship victory triggered absolute euphoria throughout the home stadium.",
    synonyms: ["elation", "ecstasy", "jubilation", "rapture"],
    difficulty: "medium",
    category: "Emotions",
    price: 35
  },
  {
    id: "melancholy",
    word: "Melancholy",
    phonetic: "/ˈmel.əŋ.kɒl.i/",
    pos: "noun",
    simpleDef: "A feeling of pensive sadness, typically with no obvious cause.",
    detailedDef: "A sustained condition of sorrowful reflection or gloomy temper.",
    example: "The rainy gray afternoon filled the quiet library with gentle melancholy.",
    synonyms: ["sorrow", "gloom", "wistfulness", "despondency"],
    difficulty: "medium",
    category: "Emotions",
    price: 40
  },
  {
    id: "nostalgia",
    word: "Nostalgia",
    phonetic: "/nɒsˈtæl.dʒə/",
    pos: "noun",
    simpleDef: "A sentimental longing for the past.",
    detailedDef: "Affectionate yearnings for a period, place, or companionship belonging to former days.",
    example: "Flipping through grandmother's photo album brought back a wave of warm nostalgia.",
    synonyms: ["reminiscence", "wistfulness", "yearning", "homesickness"],
    difficulty: "easy",
    category: "Emotions",
    price: 25
  },
  {
    id: "indignant",
    word: "Indignant",
    phonetic: "/ɪnˈdɪɡ.nənt/",
    pos: "adjective",
    simpleDef: "Feeling or showing anger at what is perceived as unfair treatment.",
    detailedDef: "Aroused by injustice, base actions, or insulting accusations.",
    example: "The citizens grew indignant when public funding was mismanaged.",
    synonyms: ["resentful", "outraged", "incensed", "provoked"],
    difficulty: "medium",
    category: "Emotions",
    price: 40
  },
  {
    id: "equanimity",
    word: "Equanimity",
    phonetic: "/ˌek.wəˈnɪm.ə.ti/",
    pos: "noun",
    simpleDef: "Mental calmness and evenness of temper, especially in difficult situations.",
    detailedDef: "Steadfast balance of mind and emotional poise under severe stress or crisis.",
    example: "She accepted the sudden news with admirable equanimity and clarity.",
    synonyms: ["composure", "calm", "serenity", "sangfroid"],
    difficulty: "hard",
    category: "Emotions",
    price: 60
  },
  {
    id: "trepidation",
    word: "Trepidation",
    phonetic: "/ˌtrep.ɪˈdeɪ.ʃən/",
    pos: "noun",
    simpleDef: "A feeling of fear or agitation about something that may happen.",
    detailedDef: "Tremulous uncertainty and nervous apprehension regarding an upcoming event.",
    example: "He stepped onto the stage with slight trepidation, but delivered an inspiring speech.",
    synonyms: ["dread", "apprehension", "anxiety", "unease"],
    difficulty: "hard",
    category: "Emotions",
    price: 65
  },
  {
    id: "apathy",
    word: "Apathy",
    phonetic: "/ˈæp.ə.θi/",
    pos: "noun",
    simpleDef: "Lack of interest, enthusiasm, or concern.",
    detailedDef: "Suppression or absence of passion, emotion, or voluntary interest.",
    example: "Widespread voter apathy often results in low election turnout.",
    synonyms: ["indifference", "unconcern", "lethargy", "passivity"],
    difficulty: "easy",
    category: "Emotions",
    price: 25
  },
  {
    id: "exuberant",
    word: "Exuberant",
    phonetic: "/ɪɡˈzjuː.bər.ənt/",
    pos: "adjective",
    simpleDef: "Filled with or characterized by lively energy and excitement.",
    detailedDef: "Lavishly joyful, high-spirited, and overflowing with enthusiastic vigor.",
    example: "The children gave an exuberant welcome to their visiting grandparents.",
    synonyms: ["ebullient", "spirited", "vivacious", "buoyant"],
    difficulty: "medium",
    category: "Emotions",
    price: 45
  },
  {
    id: "enamored",
    word: "Enamored",
    phonetic: "/ɪˈnæm.əd/",
    pos: "adjective",
    simpleDef: "Charmed, captivated, or filled with love.",
    detailedDef: "Strongly fascinated or deeply appreciative of a particular pursuit or person.",
    example: "He became entirely enamored of astrophotography after viewing Saturn's rings.",
    synonyms: ["captivated", "infatuated", "charmed", "smitten"],
    difficulty: "medium",
    category: "Emotions",
    price: 40
  },
  {
    id: "rancor",
    word: "Rancor",
    phonetic: "/ˈræŋ.kər/",
    pos: "noun",
    simpleDef: "Bitterness or resentfulness, especially when long-standing.",
    detailedDef: "Deep-seated ill will, persistent spite, and malice between rivals.",
    example: "Despite their political dispute, they resolved the treaty without lingering rancor.",
    synonyms: ["bitterness", "animosity", "spite", "malice"],
    difficulty: "hard",
    category: "Emotions",
    price: 60
  },

  // Nature (Easy, Medium, Hard)
  {
    id: "blossom",
    word: "Blossom",
    phonetic: "/ˈblɒs.əm/",
    pos: "noun",
    simpleDef: "A flower or mass of flowers on a tree or bush.",
    detailedDef: "The reproductive floral structure of seed plants; to develop into full bloom.",
    example: "Delicate cherry blossom petals drifted gently through the spring breeze.",
    synonyms: ["flower", "bloom", "efflorescence"],
    difficulty: "easy",
    category: "Nature",
    price: 20
  },
  {
    id: "canopy",
    word: "Canopy",
    phonetic: "/ˈkæn.ə.pi/",
    pos: "noun",
    simpleDef: "The high, continuous overhead layer formed by tree crowns.",
    detailedDef: "The uppermost branchy layer in a forest forming a sheltering roof.",
    example: "Sunlight filtered softly through the dense emerald canopy of the rainforest.",
    synonyms: ["awning", "cover", "treetop layer"],
    difficulty: "easy",
    category: "Nature",
    price: 20
  },
  {
    id: "meadow",
    word: "Meadow",
    phonetic: "/ˈmed.əʊ/",
    pos: "noun",
    simpleDef: "A piece of grassland, especially one used for hay or grazing.",
    detailedDef: "A low, level tract of grassland supporting wild flora and diverse pollinators.",
    example: "Wildflowers of every shade carpeted the alpine meadow in midsummer.",
    synonyms: ["pasture", "grassland", "lea", "field"],
    difficulty: "easy",
    category: "Nature",
    price: 20
  },
  {
    id: "verdant",
    word: "Verdant",
    phonetic: "/ˈvɜː.dənt/",
    pos: "adjective",
    simpleDef: "Green with grass or other rich vegetation.",
    detailedDef: "Lushly overgrown with fresh, green plant life; flourishing in green hue.",
    example: "The hikers paused to admire the verdant rolling hills stretching to the horizon.",
    synonyms: ["lush", "green", "flourishing", "leafy"],
    difficulty: "medium",
    category: "Nature",
    price: 35
  },
  {
    id: "tributary",
    word: "Tributary",
    phonetic: "/ˈtrɪb.jə.tər.i/",
    pos: "noun",
    simpleDef: "A river or stream flowing into a larger river or lake.",
    detailedDef: "A secondary watercourse contributing freshwater flow into a master drainage.",
    example: "The mountain tributary fed clear glacier meltwater into the mighty river below.",
    synonyms: ["branch", "feeder", "stream", "brook"],
    difficulty: "medium",
    category: "Nature",
    price: 40
  },
  {
    id: "dormant",
    word: "Dormant",
    phonetic: "/ˈdɔː.mənt/",
    pos: "adjective",
    simpleDef: "Temporarily inactive or in a state of rest.",
    detailedDef: "In a resting condition with suspended metabolic growth during adverse seasons.",
    example: "Deciduous trees remain dormant throughout the freezing months of winter.",
    synonyms: ["inactive", "sleeping", "hibernating", "latent"],
    difficulty: "easy",
    category: "Nature",
    price: 25
  },
  {
    id: "luminous",
    word: "Luminous",
    phonetic: "/ˈluː.mɪ.nəs/",
    pos: "adjective",
    simpleDef: "Giving off light; bright or shining.",
    detailedDef: "Emitting steady radiation that glows warmly in the darkness.",
    example: "Fireflies turned the damp woodland into a magical luminous spectacle.",
    synonyms: ["radiant", "glowing", "bright", "shining"],
    difficulty: "medium",
    category: "Nature",
    price: 35
  },
  {
    id: "petrichor",
    word: "Petrichor",
    phonetic: "/ˈpet.rɪ.kɔːr/",
    pos: "noun",
    simpleDef: "The pleasant, earthy smell that accompanies the first rain after dry weather.",
    detailedDef: "An aromatic essence produced by geosmin and airborne plant oils during rain.",
    example: "As the summer thunderstorm rolled in, the refreshing smell of petrichor filled the air.",
    synonyms: ["earthy aroma", "rain scent"],
    difficulty: "hard",
    category: "Nature",
    price: 65
  },
  {
    id: "crepuscular",
    word: "Crepuscular",
    phonetic: "/krɪˈpʌs.kjə.lər/",
    pos: "adjective",
    simpleDef: "Active primarily during twilight, dawn, or dusk.",
    detailedDef: "Pertaining to or resembling the dim light of dawn and sunset, especially of animal habits.",
    example: "Deer and fireflies are crepuscular creatures that emerge as the sun sets.",
    synonyms: ["twilight", "dusky", "dim"],
    difficulty: "hard",
    category: "Nature",
    price: 70
  },
  {
    id: "solitary",
    word: "Solitary",
    phonetic: "/ˈsɒl.ɪ.tər.i/",
    pos: "adjective",
    simpleDef: "Existing alone; without companions.",
    detailedDef: "Living or occurring separately from society or others of the same species.",
    example: "The solitary eagle soared high above the jagged mountain peaks.",
    synonyms: ["lone", "isolated", "single", "remote"],
    difficulty: "easy",
    category: "Nature",
    price: 25
  },
  {
    id: "arid",
    word: "Arid",
    phonetic: "/ˈær.ɪd/",
    pos: "adjective",
    simpleDef: "Having little or no rain; too dry to support regular vegetation.",
    detailedDef: "Exceedingly dry and barren climate marked by minimal precipitation.",
    example: "Succulents have adapted unique methods to store moisture in arid desert regions.",
    synonyms: ["dry", "parched", "barren", "waterless"],
    difficulty: "medium",
    category: "Nature",
    price: 35
  },
  {
    id: "tempest",
    word: "Tempest",
    phonetic: "/ˈtem.pɪst/",
    pos: "noun",
    simpleDef: "A violent windy storm.",
    detailedDef: "An intense meteorological disturbance accompanied by fierce winds, rain, or hail.",
    example: "The brave sailors navigated through the howling tempest to reach calm waters.",
    synonyms: ["storm", "gale", "cyclone", "hurricane"],
    difficulty: "medium",
    category: "Nature",
    price: 40
  },
  {
    id: "halcyon",
    word: "Halcyon",
    phonetic: "/ˈhæl.si.ən/",
    pos: "adjective",
    simpleDef: "Denoting a period of time in the past that was idyllically peaceful.",
    detailedDef: "Characterized by golden calm, prosperous tranquility, and serene sunshine.",
    example: "Grandpa fondly remembered the halcyon summers of his youth by the lake.",
    synonyms: ["peaceful", "golden", "idyllic", "tranquil"],
    difficulty: "hard",
    category: "Nature",
    price: 65
  },

  // Science (Easy, Medium, Hard)
  {
    id: "gravity",
    word: "Gravity",
    phonetic: "/ˈɡræv.ə.ti/",
    pos: "noun",
    simpleDef: "The fundamental force that attracts objects toward one another.",
    detailedDef: "Universal gravitational attraction proportional to mass and inversely to distance squared.",
    example: "Earth's gravity holds the atmosphere in place and keeps oceans anchored.",
    synonyms: ["gravitation", "attraction", "pull"],
    difficulty: "easy",
    category: "Science",
    price: 20
  },
  {
    id: "molecule",
    word: "Molecule",
    phonetic: "/ˈmɒl.ɪ.kjuːl/",
    pos: "noun",
    simpleDef: "A group of atoms bonded together, forming the smallest unit of a chemical compound.",
    detailedDef: "The smallest fundamental particle of an element or compound retaining chemical properties.",
    example: "A water molecule is composed of two hydrogen atoms bonded to one oxygen atom.",
    synonyms: ["particle", "chemical compound"],
    difficulty: "easy",
    category: "Science",
    price: 20
  },
  {
    id: "osmosis",
    word: "Osmosis",
    phonetic: "/ɒzˈməʊ.sɪs/",
    pos: "noun",
    simpleDef: "Movement of water molecules across a membrane from low to high solute concentration.",
    detailedDef: "Diffusion of solvent through a semipermeable membrane into a region of higher solute.",
    example: "Plant roots absorb groundwater through osmosis to sustain cellular hydration.",
    synonyms: ["diffusion", "absorption", "passage"],
    difficulty: "medium",
    category: "Science",
    price: 35
  },
  {
    id: "catalyst",
    word: "Catalyst",
    phonetic: "/ˈkæt.əl.ɪst/",
    pos: "noun",
    simpleDef: "A substance that increases the rate of a chemical reaction without undergoing permanent change.",
    detailedDef: "Any agent that provokes or accelerates substantial change or reaction.",
    example: "Enzymes serve as biological catalysts that allow cellular metabolism to occur rapidly.",
    synonyms: ["stimulus", "accelerant", "spark", "impetus"],
    difficulty: "medium",
    category: "Science",
    price: 40
  },
  {
    id: "symbiosis",
    word: "Symbiosis",
    phonetic: "/ˌsɪm.baɪˈəʊ.sɪs/",
    pos: "noun",
    simpleDef: "Interaction between two different organisms living in close physical association.",
    detailedDef: "A mutually advantageous ecological relationship between distinct biological species.",
    example: "Clownfish and sea anemones maintain a classic symbiosis for protection and food.",
    synonyms: ["cooperation", "mutualism", "interdependence"],
    difficulty: "medium",
    category: "Science",
    price: 45
  },
  {
    id: "hypothesis",
    word: "Hypothesis",
    phonetic: "/haɪˈpɒθ.ə.sɪs/",
    pos: "noun",
    simpleDef: "A proposed explanation made as a starting point for further investigation.",
    detailedDef: "A testable tentative proposition formulated empirically to guide experimentation.",
    example: "The research team devised a clear hypothesis before collecting sample data.",
    synonyms: ["theory", "conjecture", "premise", "postulate"],
    difficulty: "easy",
    category: "Science",
    price: 25
  },
  {
    id: "entropy",
    word: "Entropy",
    phonetic: "/ˈen.trə.pi/",
    pos: "noun",
    simpleDef: "A measure of disorder, randomness, or unavailable thermal energy in a system.",
    detailedDef: "Thermodynamic state variable representing degradation of matter and energy toward chaos.",
    example: "The second law of thermodynamics asserts that the entropy of an isolated system always increases.",
    synonyms: ["disorder", "randomness", "decay", "chaos"],
    difficulty: "hard",
    category: "Science",
    price: 60
  },
  {
    id: "luminescence",
    word: "Luminescence",
    phonetic: "/ˌluː.mɪˈnes.əns/",
    pos: "noun",
    simpleDef: "Emission of light by a substance not resulting from heat.",
    detailedDef: "Cold light produced by chemical, electrical, or physiological reactions.",
    example: "Deep sea anglerfish use bioluminescence to attract prey in total darkness.",
    synonyms: ["glow", "radiance", "fluorescence", "phosphorescence"],
    difficulty: "medium",
    category: "Science",
    price: 45
  },
  {
    id: "viscosity",
    word: "Viscosity",
    phonetic: "/vɪˈskɒs.ə.ti/",
    pos: "noun",
    simpleDef: "The state of being thick, sticky, and semi-fluid in consistency.",
    detailedDef: "Internal friction of a fluid that resists flow and molecular deformation.",
    example: "Motor oil with high viscosity pours slowly when exposed to freezing temperatures.",
    synonyms: ["thickness", "stickiness", "density", "cohesiveness"],
    difficulty: "medium",
    category: "Science",
    price: 40
  },
  {
    id: "equilibrium",
    word: "Equilibrium",
    phonetic: "/ˌek.wɪˈlɪb.ri.əm/",
    pos: "noun",
    simpleDef: "A state in which opposing forces or influences are balanced.",
    detailedDef: "Static or dynamic condition where competing chemical reactions or mechanical forces cancel out.",
    example: "The chemical mixture reached dynamic equilibrium with forward and reverse rates matching.",
    synonyms: ["balance", "stability", "symmetry", "poise"],
    difficulty: "medium",
    category: "Science",
    price: 45
  },
  {
    id: "scintillate",
    word: "Scintillate",
    phonetic: "/ˈsɪn.tɪ.leɪt/",
    pos: "verb",
    simpleDef: "To emit flashes of light; sparkle brilliantly.",
    detailedDef: "To throw off quick sparks or brief flashes of illumination; to display animated brilliance.",
    example: "The diamond began to scintillate vividly under the bright chandelier lights.",
    synonyms: ["sparkle", "glimmer", "flash", "twinkle"],
    difficulty: "hard",
    category: "Science",
    price: 65
  },
  {
    id: "quarks",
    word: "Quark",
    phonetic: "/kwɑːk/",
    pos: "noun",
    simpleDef: "A fundamental elementary particle that makes up hadrons like protons and neutrons.",
    detailedDef: "Subatomic constituent carrying fractional electric charges governed by strong interaction.",
    example: "Physicists classify each quark by flavors such as up, down, charm, and strange.",
    synonyms: ["subatomic particle", "corpuscle"],
    difficulty: "hard",
    category: "Science",
    price: 60
  },

  // Technology (Easy, Medium, Hard)
  {
    id: "algorithm",
    word: "Algorithm",
    phonetic: "/ˈæl.ɡə.rɪ.ðəm/",
    pos: "noun",
    simpleDef: "A process or set of step-by-step rules to be followed in calculations or problem-solving.",
    detailedDef: "Finite, unambiguous sequence of computational instructions for executing a task.",
    example: "The search engine uses a sophisticated sorting algorithm to order relevant results.",
    synonyms: ["procedure", "formula", "recipe", "protocol"],
    difficulty: "easy",
    category: "Technology",
    price: 25
  },
  {
    id: "cache",
    word: "Cache",
    phonetic: "/kæʃ/",
    pos: "noun",
    simpleDef: "A hardware or software component that stores data for fast subsequent retrieval.",
    detailedDef: "Auxiliary high-speed storage buffer used to accelerate recurrent computational access.",
    example: "Clearing the web browser cache resolved the issue with outdated webpage graphics.",
    synonyms: ["buffer", "store", "repository", "hoard"],
    difficulty: "easy",
    category: "Technology",
    price: 20
  },
  {
    id: "encryption",
    word: "Encryption",
    phonetic: "/ɪnˈkrɪp.ʃən/",
    pos: "noun",
    simpleDef: "The process of converting information into secret code to prevent unauthorized access.",
    detailedDef: "Cryptographic mathematical encoding of plain text into unintelligible ciphertext.",
    example: "End-to-end encryption ensures that only sender and recipient can read private messages.",
    synonyms: ["encoding", "ciphering", "scrambling"],
    difficulty: "easy",
    category: "Technology",
    price: 25
  },
  {
    id: "latency",
    word: "Latency",
    phonetic: "/ˈleɪ.tən.si/",
    pos: "noun",
    simpleDef: "The time delay between a prompt and the corresponding response.",
    detailedDef: "Temporal interval separating signal origination from its receipt or execution.",
    example: "Fiber-optic cabling minimizes network latency during international video calls.",
    synonyms: ["delay", "lag", "interval", "hesitation"],
    difficulty: "medium",
    category: "Technology",
    price: 35
  },
  {
    id: "bandwidth",
    word: "Bandwidth",
    phonetic: "/ˈbænd.wɪtθ/",
    pos: "noun",
    simpleDef: "The maximum amount of data transmitted over an internet connection in a given time.",
    detailedDef: "Capacity of a wired or wireless telecommunications network channel measured in bit rates.",
    example: "Streaming 4K video requires sufficient broadband bandwidth to prevent buffering.",
    synonyms: ["capacity", "throughput", "transmission rate"],
    difficulty: "easy",
    category: "Technology",
    price: 25
  },
  {
    id: "modular",
    word: "Modular",
    phonetic: "/ˈmɒdʒ.ə.lər/",
    pos: "adjective",
    simpleDef: "Employing or made of independent separable components.",
    detailedDef: "Constructed with standardized units allowing flexible configuration and maintenance.",
    example: "The software architect built a modular codebase where features can be upgraded independently.",
    synonyms: ["component-based", "flexible", "segmented", "compartmentalized"],
    difficulty: "medium",
    category: "Technology",
    price: 40
  },
  {
    id: "redundancy",
    word: "Redundancy",
    phonetic: "/rɪˈdʌn.dən.si/",
    pos: "noun",
    simpleDef: "Inclusion of extra components functioning in case of failure of other parts.",
    detailedDef: "Intentional duplication of critical hardware or paths to guarantee fault tolerance.",
    example: "Cloud data centers rely on power redundancy so backup generators kick in instantly.",
    synonyms: ["duplication", "backup", "spare capacity"],
    difficulty: "medium",
    category: "Technology",
    price: 45
  },
  {
    id: "deprecated",
    word: "Deprecated",
    phonetic: "/ˈdep.rɪ.keɪ.tɪd/",
    pos: "adjective",
    simpleDef: "Declared obsolete and recommended against use in programming.",
    detailedDef: "Maintained temporarily for backwards compatibility but slated for impending removal.",
    example: "Developers replaced the deprecated authentication method with a modern secure token.",
    synonyms: ["obsolete", "phased-out", "superseded", "discontinued"],
    difficulty: "hard",
    category: "Technology",
    price: 60
  },
  {
    id: "asynchronous",
    word: "Asynchronous",
    phonetic: "/eɪˈsɪŋ.krə.nəs/",
    pos: "adjective",
    simpleDef: "Not occurring at the same time; happening independently of the primary program flow.",
    detailedDef: "Executing operations concurrently without blocking execution while waiting for completion.",
    example: "Asynchronous programming ensures the user interface stays responsive while downloading data.",
    synonyms: ["non-blocking", "independent", "concurrent"],
    difficulty: "hard",
    category: "Technology",
    price: 65
  },
  {
    id: "telemetry",
    word: "Telemetry",
    phonetic: "/təˈlem.ə.tri/",
    pos: "noun",
    simpleDef: "The automatic recording and transmission of data from remote or inaccessible sources.",
    detailedDef: "Remote automated sensing, wireless monitoring, and computational telemetry metrics.",
    example: "Rocket engineers analyzed real-time telemetry transmitted during atmospheric re-entry.",
    synonyms: ["remote monitoring", "data collection", "surveillance"],
    difficulty: "hard",
    category: "Technology",
    price: 65
  },
  {
    id: "firmware",
    word: "Firmware",
    phonetic: "/ˈfɜːm.weər/",
    pos: "noun",
    simpleDef: "Permanent software programmed into a read-only memory device.",
    detailedDef: "Specialized low-level control code embedded directly inside microcontrollers.",
    example: "Updating the router firmware fixed the wireless connectivity dropouts.",
    synonyms: ["microcode", "embedded software"],
    difficulty: "medium",
    category: "Technology",
    price: 40
  },
  {
    id: "heuristic",
    word: "Heuristic",
    phonetic: "/hjuːˈrɪs.tɪk/",
    pos: "adjective",
    simpleDef: "Enabling a person or algorithm to discover or learn something for themselves.",
    detailedDef: "Practical problem-solving method not guaranteed optimal but sufficient for quick approximations.",
    example: "The antivirus program uses heuristic analysis to detect novel malware variants.",
    synonyms: ["exploratory", "rule-of-thumb", "empirical", "trial-and-error"],
    difficulty: "hard",
    category: "Technology",
    price: 70
  },

  // Business (Easy, Medium, Hard)
  {
    id: "budget",
    word: "Budget",
    phonetic: "/ˈbʌdʒ.ɪt/",
    pos: "noun",
    simpleDef: "An estimate of income and expenditure for a set period of time.",
    detailedDef: "Comprehensive financial projection allocating capital resources to prioritized operations.",
    example: "The marketing director submitted an annual budget to fund regional promotional campaigns.",
    synonyms: ["allowance", "financial plan", "allocation", "quota"],
    difficulty: "easy",
    category: "Business",
    price: 20
  },
  {
    id: "revenue",
    word: "Revenue",
    phonetic: "/ˈrev.ən.juː/",
    pos: "noun",
    simpleDef: "Income, especially when of a company or organization of a substantial nature.",
    detailedDef: "Total monetary receipts yielded by operational commercial trade and services.",
    example: "Quarterly sales revenue exceeded investor forecasts by fifteen percent.",
    synonyms: ["income", "proceeds", "turnover", "earnings"],
    difficulty: "easy",
    category: "Business",
    price: 20
  },
  {
    id: "collaboration",
    word: "Collaboration",
    phonetic: "/kəˌlæb.əˈreɪ.ʃən/",
    pos: "noun",
    simpleDef: "The action of working with someone to produce or create something.",
    detailedDef: "Cooperative intellectual and operational enterprise across stakeholders.",
    example: "Close collaboration between design and engineering teams resulted in an award-winning app.",
    synonyms: ["cooperation", "partnership", "teamwork", "alliance"],
    difficulty: "easy",
    category: "Business",
    price: 20
  },
  {
    id: "leverage",
    word: "Leverage",
    phonetic: "/ˈlev.ər.ɪdʒ/",
    pos: "verb",
    simpleDef: "To use something to maximum advantage.",
    detailedDef: "To exploit existing strategic assets, debt, or relationships to gain disproportionate benefits.",
    example: "The startup aims to leverage customer testimonials to secure enterprise contracts.",
    synonyms: ["utilize", "capitalize on", "harness", "exploit"],
    difficulty: "medium",
    category: "Business",
    price: 35
  },
  {
    id: "benchmark",
    word: "Benchmark",
    phonetic: "/ˈbentʃ.mɑːk/",
    pos: "noun",
    simpleDef: "A standard or point of reference against which things may be compared.",
    detailedDef: "An established criterion or metric serving as a comparative quality measure.",
    example: "Customer satisfaction rates set a high benchmark that competing retailers strive to match.",
    synonyms: ["standard", "criterion", "gauge", "yardstick"],
    difficulty: "medium",
    category: "Business",
    price: 40
  },
  {
    id: "synergy",
    word: "Synergy",
    phonetic: "/ˈsɪn.ə.dʒi/",
    pos: "noun",
    simpleDef: "The combined power of a group of things when working together that is greater than the sum of separate parts.",
    detailedDef: "Cooperative interaction yielding enhanced collective output unavailable in isolation.",
    example: "The corporate merger created operational synergy that slashed overhead expenses.",
    synonyms: ["cooperation", "symbiosis", "harmony", "combined effort"],
    difficulty: "medium",
    category: "Business",
    price: 45
  },
  {
    id: "solvency",
    word: "Solvency",
    phonetic: "/ˈsɒl.vən.si/",
    pos: "noun",
    simpleDef: "The ability to pay all financial debts and meet long-term obligations.",
    detailedDef: "Financial stability evidenced by assets exceeding total legal liabilities.",
    example: "The bank audit confirmed the firm's robust solvency before issuing the credit facility.",
    synonyms: ["financial health", "liquidity", "creditworthiness"],
    difficulty: "medium",
    category: "Business",
    price: 45
  },
  {
    id: "diversify",
    word: "Diversify",
    phonetic: "/daɪˈvɜː.sɪ.faɪ/",
    pos: "verb",
    simpleDef: "To enlarge or vary by widening the range of products or investments.",
    detailedDef: "Spreading capital exposure across multiple sectors to mitigate aggregate systemic risk.",
    example: "Investors diversify their portfolios across bonds, equities, and real estate.",
    synonyms: ["expand", "vary", "branch out", "broaden"],
    difficulty: "medium",
    category: "Business",
    price: 40
  },
  {
    id: "amortization",
    word: "Amortization",
    phonetic: "/əˌmɔː.tɪˈzeɪ.ʃən/",
    pos: "noun",
    simpleDef: "The gradual reduction or write-off of an initial cost over regular periods.",
    detailedDef: "Systematic periodic accounting expensing of intangible assets or debt liquidation.",
    example: "The financial schedule outlined thirty years of monthly loan amortization.",
    synonyms: ["depreciation", "repayment", "liquidation", "installment plan"],
    difficulty: "hard",
    category: "Business",
    price: 65
  },
  {
    id: "fiduciary",
    word: "Fiduciary",
    phonetic: "/fɪˈdjuː.ʃə.ri/",
    pos: "adjective",
    simpleDef: "Involving trust, especially regarding the relationship between a trustee and beneficiary.",
    detailedDef: "Held in ethical and legal trust; duty to act solely in the best economic interest of another.",
    example: "Pension fund managers have a solemn fiduciary duty to safeguard retirees' savings.",
    synonyms: ["trustee-based", "custodial", "confidential", "ethical"],
    difficulty: "hard",
    category: "Business",
    price: 70
  },
  {
    id: "arbitrage",
    word: "Arbitrage",
    phonetic: "/ˈɑː.bɪ.trɑːʒ/",
    pos: "noun",
    simpleDef: "The simultaneous buying and selling of securities in different markets to take advantage of differing prices.",
    detailedDef: "Exploiting brief price discrepancies of identical financial assets across market exchanges.",
    example: "High-frequency algorithms execute currency arbitrage within milliseconds.",
    synonyms: ["market trading", "price-spread exploitation"],
    difficulty: "hard",
    category: "Business",
    price: 70
  },

  // Literature (Easy, Medium, Hard)
  {
    id: "metaphor",
    word: "Metaphor",
    phonetic: "/ˈmet.ə.fɔːr/",
    pos: "noun",
    simpleDef: "A figure of speech in which a word or phrase is applied to an object to which it is not literally applicable.",
    detailedDef: "Rhetorical comparison stating that one thing is another to illuminate symbolic meaning.",
    example: "Shakespeare used the metaphor 'All the world's a stage' to contemplate human lives.",
    synonyms: ["allegory", "figure of speech", "analogy", "symbol"],
    difficulty: "easy",
    category: "Literature",
    price: 20
  },
  {
    id: "prologue",
    word: "Prologue",
    phonetic: "/ˈprəʊ.lɒɡ/",
    pos: "noun",
    simpleDef: "A separate introductory section of a literary or musical work.",
    detailedDef: "Prefatory discourse setting dramatic context or thematic tone before the main narrative.",
    example: "The novel opens with an intriguing prologue describing an ancient forgotten prophecy.",
    synonyms: ["introduction", "preface", "foreword", "preamble"],
    difficulty: "easy",
    category: "Literature",
    price: 20
  },
  {
    id: "dialogue",
    word: "Dialogue",
    phonetic: "/ˈdaɪ.ə.lɒɡ/",
    pos: "noun",
    simpleDef: "Conversation between two or more people as a feature of a book or play.",
    detailedDef: "Verbal exchange between characters revealing motivation, conflict, and voice.",
    example: "The playwright wrote sharp, witty dialogue that kept the theater audience laughing.",
    synonyms: ["conversation", "discourse", "talk", "exchange"],
    difficulty: "easy",
    category: "Literature",
    price: 20
  },
  {
    id: "allusion",
    word: "Allusion",
    phonetic: "/əˈluː.ʒən/",
    pos: "noun",
    simpleDef: "An expression designed to call something to mind without mentioning it explicitly.",
    detailedDef: "Indirect literary or historical reference inviting the reader to discern implied connections.",
    example: "Her casual reference to Achilles' heel was an allusion to his singular vulnerability.",
    synonyms: ["reference", "intimation", "hint", "insinuation"],
    difficulty: "medium",
    category: "Literature",
    price: 35
  },
  {
    id: "hyperbole",
    word: "Hyperbole",
    phonetic: "/haɪˈpɜː.bəl.i/",
    pos: "noun",
    simpleDef: "Exaggerated statements or claims not meant to be taken literally.",
    detailedDef: "Intentional rhetorical exaggeration used to emphasize emotional drama or humor.",
    example: "Saying 'I have told you a million times' is a textbook example of hyperbole.",
    synonyms: ["exaggeration", "overstatement", "embellishment"],
    difficulty: "medium",
    category: "Literature",
    price: 40
  },
  {
    id: "irony",
    word: "Irony",
    phonetic: "/ˈaɪ.rə.ni/",
    pos: "noun",
    simpleDef: "The expression of one's meaning by using language that normally signifies the opposite.",
    detailedDef: "Contrast between expectation and reality, often delivering poignant comedic or tragic effect.",
    example: "The irony was palpable when the fire station caught fire due to unattended candles.",
    synonyms: ["sarcasm", "paradox", "incongruity", "mockery"],
    difficulty: "easy",
    category: "Literature",
    price: 25
  },
  {
    id: "motif",
    word: "Motif",
    phonetic: "/məʊˈtiːf/",
    pos: "noun",
    simpleDef: "A distinctive feature or dominant idea in an artistic or literary composition.",
    detailedDef: "Recurring symbolic element throughout a narrative that reinforces major themes.",
    example: "The ticking clock is a recurring motif representing mortality throughout the play.",
    synonyms: ["theme", "concept", "leitmotif", "pattern"],
    difficulty: "medium",
    category: "Literature",
    price: 40
  },
  {
    id: "epiphany",
    word: "Epiphany",
    phonetic: "/ɪˈpɪf.ən.i/",
    pos: "noun",
    simpleDef: "A moment of sudden revelation or profound insight.",
    detailedDef: "Spontaneous intuitive grasp of essential reality triggered by an ordinary experience.",
    example: "While watching rain streaks on the glass, she experienced a sudden epiphany about her true calling.",
    synonyms: ["revelation", "realization", "insight", "awakening"],
    difficulty: "medium",
    category: "Literature",
    price: 45
  },
  {
    id: "soliloquy",
    word: "Soliloquy",
    phonetic: "/səˈlɪl.ə.kwi/",
    pos: "noun",
    simpleDef: "An act of speaking one's thoughts aloud when by oneself on stage.",
    detailedDef: "Dramatic monologue voicing a character's innermost turmoil without listeners.",
    example: "Hamlet's famous 'To be or not to be' soliloquy wrestles with existential despair.",
    synonyms: ["monologue", "speech", "aside"],
    difficulty: "hard",
    category: "Literature",
    price: 60
  },
  {
    id: "allegory",
    word: "Allegory",
    phonetic: "/ˈæl.ə.ɡər.i/",
    pos: "noun",
    simpleDef: "A story, poem, or picture that can be interpreted to reveal a hidden symbolic meaning.",
    detailedDef: "Extended metaphor wherein characters and events represent moral or political truths.",
    example: "George Orwell's Animal Farm serves as a famous political allegory.",
    synonyms: ["parable", "fable", "symbolic tale", "apologue"],
    difficulty: "medium",
    category: "Literature",
    price: 45
  },
  {
    id: "bildungsroman",
    word: "Bildungsroman",
    phonetic: "/ˈbɪl.dʊŋz.rəʊˌmɑːn/",
    pos: "noun",
    simpleDef: "A coming-of-age novel focusing on the psychological and moral growth of the protagonist.",
    detailedDef: "Literary genre charting a youth's development through hardships into mature wisdom.",
    example: "Jane Eyre is widely studied as a quintessential Victorian bildungsroman.",
    synonyms: ["coming-of-age story", "formative novel"],
    difficulty: "hard",
    category: "Literature",
    price: 70
  },
  {
    id: "catharsis",
    word: "Catharsis",
    phonetic: "/kəˈθɑː.sɪs/",
    pos: "noun",
    simpleDef: "The process of releasing and thereby providing relief from strong emotions.",
    detailedDef: "Emotional purgation and spiritual renewal induced by participating in tragic art.",
    example: "The dramatic final scene provided an overwhelming sense of catharsis for the weeping audience.",
    synonyms: ["purging", "release", "cleansing", "deliverance"],
    difficulty: "hard",
    category: "Literature",
    price: 65
  },

  // Advanced Vocabulary (Medium & Hard)
  {
    id: "eloquent",
    word: "Eloquent",
    phonetic: "/ˈel.ə.kwənt/",
    pos: "adjective",
    simpleDef: "Fluent or persuasive in speaking or writing.",
    detailedDef: "Articulating ideas with graceful poise, compelling force, and poetic charm.",
    example: "His eloquent defense persuaded the jury to reconsider their verdict.",
    synonyms: ["articulate", "persuasive", "expressive", "fluent"],
    difficulty: "easy",
    category: "Advanced Vocabulary",
    price: 25
  },
  {
    id: "meticulous",
    word: "Meticulous",
    phonetic: "/məˈtɪk.jə.ləs/",
    pos: "adjective",
    simpleDef: "Showing great attention to detail; very careful and precise.",
    detailedDef: "Extremely finicky and diligent about small nuances and perfectionism.",
    example: "The restorer took meticulous care cleaning centuries-old oil pigments.",
    synonyms: ["thorough", "precise", "scrupulous", "painstaking"],
    difficulty: "easy",
    category: "Advanced Vocabulary",
    price: 25
  },
  {
    id: "resilient",
    word: "Resilient",
    phonetic: "/rɪˈzɪl.jənt/",
    pos: "adjective",
    simpleDef: "Able to withstand or recover quickly from difficult conditions.",
    detailedDef: "Possessing buoyant elastic fortitude that bounces back unharmed from adversity.",
    example: "The resilient community rebuilt their town stronger after the flood.",
    synonyms: ["tenacious", "tough", "pliable", "hardy"],
    difficulty: "easy",
    category: "Advanced Vocabulary",
    price: 25
  },
  {
    id: "cacophony",
    word: "Cacophony",
    phonetic: "/kəˈkɒf.ən.i/",
    pos: "noun",
    simpleDef: "A harsh, discordant mixture of sounds.",
    detailedDef: "Inharmonious clashing acoustic chaos that grates roughly upon the ear.",
    example: "The marketplace was a bewildering cacophony of shouting vendors and car horns.",
    synonyms: ["din", "racket", "discord", "clamor"],
    difficulty: "medium",
    category: "Advanced Vocabulary",
    price: 40
  },
  {
    id: "garrulous",
    word: "Garrulous",
    phonetic: "/ˈɡær.əl.əs/",
    pos: "adjective",
    simpleDef: "Excessively talkative, especially on trivial matters.",
    detailedDef: "Given to rambling conversation and loquacious chatter without restraint.",
    example: "The garrulous neighbor kept us at the fence for an hour recounting his lawn care tips.",
    synonyms: ["talkative", "loquacious", "voluble", "chatty"],
    difficulty: "medium",
    category: "Advanced Vocabulary",
    price: 45
  },
  {
    id: "ephemeral_adv",
    word: "Evanescent",
    phonetic: "/ˌev.əˈnes.ənt/",
    pos: "adjective",
    simpleDef: "Soon passing out of sight, memory, or existence; quickly fading.",
    detailedDef: "Vanishing like vapor; delicate and imperceptibly vanishing from presence.",
    example: "A rainbow is an evanescent marvel that graces the sky for only a few fleeting moments.",
    synonyms: ["fleeting", "transient", "fading", "fugitive"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 65
  },
  {
    id: "ineffable",
    word: "Ineffable",
    phonetic: "/ɪnˈef.ə.bəl/",
    pos: "adjective",
    simpleDef: "Too great or extreme to be expressed or described in words.",
    detailedDef: "Defying linguistic description; unutterable sheer awe and transcendence.",
    example: "Standing atop the snowcapped mountain summit, she felt an ineffable peace.",
    synonyms: ["indescribable", "unutterable", "beyond words", "transcendent"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 65
  },
  {
    id: "mellifluous",
    word: "Mellifluous",
    phonetic: "/meˈlɪf.lu.əs/",
    pos: "adjective",
    simpleDef: "Sweet or musical; pleasant to hear.",
    detailedDef: "Flowing with sweet honeyed rhythm; delightfully soothing and harmonious.",
    example: "The radio announcer possessed a deep, mellifluous voice loved by listeners.",
    synonyms: ["dulcet", "honeyed", "euphonious", "melodious"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 70
  },
  {
    id: "obfuscate",
    word: "Obfuscate",
    phonetic: "/ˈɒb.fʌs.keɪt/",
    pos: "verb",
    simpleDef: "To make obscure, unclear, or unintelligible.",
    detailedDef: "Deliberately clouding truth or perception through evasive complex language.",
    example: "The spokesperson attempted to obfuscate the facts by citing irrelevant technicalities.",
    synonyms: ["confuse", "muddle", "obscure", "cloud"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 65
  },
  {
    id: "panacea",
    word: "Panacea",
    phonetic: "/ˌpæn.əˈsiː.ə/",
    pos: "noun",
    simpleDef: "A solution or remedy for all difficulties or diseases.",
    detailedDef: "A hypothetical cure-all; universal solution resolving complex structural ailments.",
    example: "Technology is a helpful tool, but it should not be viewed as a panacea for education.",
    synonyms: ["cure-all", "elixir", "universal remedy"],
    difficulty: "medium",
    category: "Advanced Vocabulary",
    price: 45
  },
  {
    id: "quixotic",
    word: "Quixotic",
    phonetic: "/kwɪkˈsɒt.ɪk/",
    pos: "adjective",
    simpleDef: "Exceedingly idealistic; unrealistic and impractical.",
    detailedDef: "Chivalrous and foolishly romantic in noble aims without regard to real practicality.",
    example: "His quixotic quest to build a perpetual motion machine drained his life savings.",
    synonyms: ["idealistic", "visionary", "romantic", "starry-eyed"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 70
  },
  {
    id: "sagacious",
    word: "Sagacious",
    phonetic: "/səˈɡeɪ.ʃəs/",
    pos: "adjective",
    simpleDef: "Having or showing keen mental discernment and good judgment.",
    detailedDef: "Gifted with profound wisdom, shrewd perceptiveness, and sound counsel.",
    example: "The village elders offered sagacious advice that settled the long-standing boundary dispute.",
    synonyms: ["wise", "shrewd", "astute", "discerning"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 70
  },
  {
    id: "vicarious",
    word: "Vicarious",
    phonetic: "/vɪˈkeə.ri.əs/",
    pos: "adjective",
    simpleDef: "Experienced in the imagination through the feelings or actions of another person.",
    detailedDef: "Participated in secondhand; felt empathetically through another's triumphs or pains.",
    example: "Avid readers derive vicarious thrill from accompanying daring explorers on expeditions.",
    synonyms: ["indirect", "secondhand", "substitute", "empathetic"],
    difficulty: "medium",
    category: "Advanced Vocabulary",
    price: 45
  },
  {
    id: "zealous",
    word: "Zealous",
    phonetic: "/ˈzel.əs/",
    pos: "adjective",
    simpleDef: "Having or showing zeal; passionate and fervent.",
    detailedDef: "Marked by vigorous devotion, intense partisanship, and tireless dedication.",
    example: "The zealous volunteers planted hundreds of saplings throughout the weekend.",
    synonyms: ["fervent", "ardent", "passionate", "devoted"],
    difficulty: "easy",
    category: "Advanced Vocabulary",
    price: 25
  },
  {
    id: "alacrity",
    word: "Alacrity",
    phonetic: "/əˈlæk.rə.ti/",
    pos: "noun",
    simpleDef: "Brisk and cheerful readiness.",
    detailedDef: "Prompt, eager, and enthusiastic willingness to perform a task.",
    example: "The eager puppy fetched the tennis ball with boundless alacrity.",
    synonyms: ["eagerness", "promptness", "keenness", "readiness"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 65
  },
  {
    id: "capricious",
    word: "Capricious",
    phonetic: "/kəˈprɪʃ.əs/",
    pos: "adjective",
    simpleDef: "Given to sudden and unaccountable changes of mood or behavior.",
    detailedDef: "Unpredictably impulsive, erratic, and swayed by fleeting whims.",
    example: "The mountain weather proved capricious, turning from brilliant sunshine to blizzard in minutes.",
    synonyms: ["fickle", "whimsical", "unpredictable", "volatile"],
    difficulty: "medium",
    category: "Advanced Vocabulary",
    price: 45
  },
  {
    id: "enigma",
    word: "Enigma",
    phonetic: "/ɪˈnɪɡ.mə/",
    pos: "noun",
    simpleDef: "A person or thing that is mysterious, puzzling, or difficult to understand.",
    detailedDef: "An impenetrable riddle or conundrum defying straightforward comprehension.",
    example: "The origin of the prehistoric stone circle remains an alluring historical enigma.",
    synonyms: ["mystery", "puzzle", "riddle", "conundrum"],
    difficulty: "easy",
    category: "Advanced Vocabulary",
    price: 25
  },
  {
    id: "gregarious",
    word: "Gregarious",
    phonetic: "/ɡrɪˈɡeə.ri.əs/",
    pos: "adjective",
    simpleDef: "Fond of company; sociable.",
    detailedDef: "Inherently inclined to associate with flocks or herds; warm, outgoing, and communicative.",
    example: "As a gregarious host, she effortlessly introduced strangers and kept everyone entertained.",
    synonyms: ["sociable", "outgoing", "companionable", "convivial"],
    difficulty: "medium",
    category: "Advanced Vocabulary",
    price: 40
  },
  {
    id: "harangue",
    word: "Harangue",
    phonetic: "/həˈræŋ/",
    pos: "noun",
    simpleDef: "A lengthy and aggressive speech.",
    detailedDef: "A ranting lecture or tirade delivered before a public audience with vehement fervor.",
    example: "The coach delivered a fiery harangue at halftime to shake the team out of complacency.",
    synonyms: ["tirade", "diatribe", "rant", "lecture"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 65
  },
  {
    id: "immutable",
    word: "Immutable",
    phonetic: "/ɪˈmjuː.tə.bəl/",
    pos: "adjective",
    simpleDef: "Unchanging over time or unable to be changed.",
    detailedDef: "Exempt from alteration, evolutionary shift, or internal decay.",
    example: "The fundamental laws of classical physics were once regarded as entirely immutable.",
    synonyms: ["unchangeable", "fixed", "permanent", "unalterable"],
    difficulty: "medium",
    category: "Advanced Vocabulary",
    price: 45
  },
  {
    id: "juxtaposition",
    word: "Juxtaposition",
    phonetic: "/ˌdʒʌk.stə.pəˈzɪʃ.ən/",
    pos: "noun",
    simpleDef: "The fact of two things being seen or placed close together with contrasting effect.",
    detailedDef: "Side-by-side positioning of dissimilar elements to highlight contrasts and conceptual irony.",
    example: "The striking juxtaposition of ancient ruins alongside glass skyscrapers created a surreal cityscape.",
    synonyms: ["contrast", "comparison", "collocation", "proximity"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 70
  },
  {
    id: "kinetic",
    word: "Kinetic",
    phonetic: "/kɪˈnet.ɪk/",
    pos: "adjective",
    simpleDef: "Relating to or resulting from motion.",
    detailedDef: "Characterized by dynamic energetic movement and physical momentum.",
    example: "The modern dance performance was filled with explosive kinetic energy.",
    synonyms: ["dynamic", "active", "moving", "energizing"],
    difficulty: "easy",
    category: "Advanced Vocabulary",
    price: 25
  },
  {
    id: "lethargic",
    word: "Lethargic",
    phonetic: "/ləˈθɑː.dʒɪk/",
    pos: "adjective",
    simpleDef: "Affected by lethargy; sluggish and apathetic.",
    detailedDef: "Lacking normal alertness and vigor due to fatigue, illness, or oppressive heat.",
    example: "The sweltering afternoon left the family feeling drowsy and delightfully lethargic.",
    synonyms: ["sluggish", "slothful", "listless", "inert"],
    difficulty: "easy",
    category: "Advanced Vocabulary",
    price: 25
  },
  {
    id: "magnanimous",
    word: "Magnanimous",
    phonetic: "/mæɡˈnæn.ɪ.məs/",
    pos: "adjective",
    simpleDef: "Generous or forgiving, especially toward a rival or less powerful person.",
    detailedDef: "Exhibiting noble greatness of spirit and chivalrous clemency without pettiness.",
    example: "In a magnanimous gesture, the victor praised his opponent's valor and shared the stage.",
    synonyms: ["generous", "noble", "charitable", "benevolent"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 70
  },
  {
    id: "nefarious",
    word: "Nefarious",
    phonetic: "/nɪˈfeə.ri.əs/",
    pos: "adjective",
    simpleDef: "Wicked, villainous, or criminal.",
    detailedDef: "Flagrantly reprehensible and evil in motive or execution.",
    example: "The detective uncovered a nefarious conspiracy to siphon treasury assets.",
    synonyms: ["wicked", "villainous", "heinous", "sinister"],
    difficulty: "medium",
    category: "Advanced Vocabulary",
    price: 45
  },
  {
    id: "ostentatious",
    word: "Ostentatious",
    phonetic: "/ˌɒs.tenˈteɪ.ʃəs/",
    pos: "adjective",
    simpleDef: "Characterized by vulgar or pretentious display; designed to impress or attract notice.",
    detailedDef: "Flashy and flamboyant boasting intended to flaunt personal wealth or vanity.",
    example: "His ostentatious gold watch and loud sports car drew bewildered stares.",
    synonyms: ["showy", "pretentious", "flamboyant", "gaudy"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 65
  },
  {
    id: "plethora",
    word: "Plethora",
    phonetic: "/ˈpleθ.ər.ə/",
    pos: "noun",
    simpleDef: "A large or excessive amount of something.",
    detailedDef: "Superabundance, overfullness, or an oversupply beyond immediate necessity.",
    example: "The digital library offers a plethora of resources for independent researchers.",
    synonyms: ["abundance", "surfeit", "profusion", "excess"],
    difficulty: "medium",
    category: "Advanced Vocabulary",
    price: 40
  },
  {
    id: "querulous",
    word: "Querulous",
    phonetic: "/ˈkwer.ə.ləs/",
    pos: "adjective",
    simpleDef: "Complaining in a petulant or whining manner.",
    detailedDef: "Habitually fault-finding, whiny, and quick to express discontent.",
    example: "The weary travelers grew querulous as the flight delay stretched into midnight.",
    synonyms: ["petulant", "peevish", "whiny", "fretful"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 70
  },
  {
    id: "recalcitrant",
    word: "Recalcitrant",
    phonetic: "/rɪˈkæl.sɪ.trənt/",
    pos: "adjective",
    simpleDef: "Having an obstinately uncooperative attitude toward authority or discipline.",
    detailedDef: "Defiantly resisting management, direction, or restraint with stubborn hostility.",
    example: "The recalcitrant donkey refused to budge an inch despite gentle coaxing.",
    synonyms: ["unruly", "defiant", "stubborn", "insubordinate"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 70
  },
  {
    id: "surreptitious",
    word: "Surreptitious",
    phonetic: "/ˌsʌr.əpˈtɪʃ.əs/",
    pos: "adjective",
    simpleDef: "Kept secret, especially because it would not be approved of.",
    detailedDef: "Executed stealthily, clandestine, and carefully concealed from observation.",
    example: "She took a surreptitious glance at her phone beneath the seminar table.",
    synonyms: ["secret", "stealthy", "clandestine", "covert"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 70
  },
  {
    id: "taciturn",
    word: "Taciturn",
    phonetic: "/ˈtæs.ɪ.tɜːn/",
    pos: "adjective",
    simpleDef: "Reserved or uncommunicative in speech; saying little.",
    detailedDef: "Temperamentally quiet, disinclined to casual talk, and sparing of words.",
    example: "The old sea captain was a taciturn man who only spoke when navigation required.",
    synonyms: ["reserved", "uncommunicative", "reticent", "quiet"],
    difficulty: "medium",
    category: "Advanced Vocabulary",
    price: 45
  },
  {
    id: "unfettered",
    word: "Unfettered",
    phonetic: "/ʌnˈfet.əd/",
    pos: "adjective",
    simpleDef: "Not confined or restricted; free from shackles.",
    detailedDef: "Unrestrained by conventional limits, bureaucracy, or physical impediment.",
    example: "The creative studio encouraged unfettered imagination during brainstorming sessions.",
    synonyms: ["unrestrained", "uninhibited", "free", "unshackled"],
    difficulty: "medium",
    category: "Advanced Vocabulary",
    price: 40
  },
  {
    id: "venerable",
    word: "Venerable",
    phonetic: "/ˈven.ər.ə.bəl/",
    pos: "adjective",
    simpleDef: "Accorded a great deal of respect, especially because of age, wisdom, or character.",
    detailedDef: "Hallowed by honorable service, ancient dignity, or sacred distinction.",
    example: "The university was founded within venerable stone halls that date back centuries.",
    synonyms: ["respected", "revered", "hallowed", "esteemed"],
    difficulty: "medium",
    category: "Advanced Vocabulary",
    price: 40
  },
  {
    id: "winsome",
    word: "Winsome",
    phonetic: "/ˈwɪn.səm/",
    pos: "adjective",
    simpleDef: "Attractive or appealing in appearance or character.",
    detailedDef: "Engagingly charming, sweet-tempered, and innocently delightful.",
    example: "She greeted every newcomer with a winsome smile that dispelled awkwardness.",
    synonyms: ["charming", "appealing", "delightful", "engaging"],
    difficulty: "medium",
    category: "Advanced Vocabulary",
    price: 40
  },
  {
    id: "zenith",
    word: "Zenith",
    phonetic: "/ˈzen.ɪθ/",
    pos: "noun",
    simpleDef: "The highest point reached by a celestial or other object; apex.",
    detailedDef: "The culminating pinnacle of power, achievement, success, or celestial elevation.",
    example: "At the zenith of her career, the soprano performed before royal dignitaries worldwide.",
    synonyms: ["pinnacle", "peak", "apex", "summit"],
    difficulty: "medium",
    category: "Advanced Vocabulary",
    price: 45
  },
  {
    id: "astute",
    word: "Astute",
    phonetic: "/əˈstjuːt/",
    pos: "adjective",
    simpleDef: "Having or showing an ability to accurately assess situations or people.",
    detailedDef: "Possessing sharp practical intelligence and discerning mental shrewdness.",
    example: "Her astute market observations allowed the fund to weather economic downturns.",
    synonyms: ["shrewd", "sharp", "clever", "perceptive"],
    difficulty: "easy",
    category: "Everyday English",
    price: 25
  },
  {
    id: "benevolent",
    word: "Benevolent",
    phonetic: "/bəˈnev.əl.ənt/",
    pos: "adjective",
    simpleDef: "Well meaning and kindly.",
    detailedDef: "Marked by an inclination to do good, relieve suffering, and bestow generosity.",
    example: "The benevolent benefactor endowed scholarships for underprivileged scholars.",
    synonyms: ["kind", "generous", "charitable", "magnanimous"],
    difficulty: "easy",
    category: "Emotions",
    price: 25
  },
  {
    id: "candid",
    word: "Candid",
    phonetic: "/ˈkæn.dɪd/",
    pos: "adjective",
    simpleDef: "Truthful and straightforward; frank.",
    detailedDef: "Free from bias, reservation, or diplomatic disguise; openly honest.",
    example: "We appreciated her candid appraisal of our proposal's realistic strengths and flaws.",
    synonyms: ["frank", "honest", "direct", "forthright"],
    difficulty: "easy",
    category: "Everyday English",
    price: 20
  },
  {
    id: "deference",
    word: "Deference",
    phonetic: "/ˈdef.ər.əns/",
    pos: "noun",
    simpleDef: "Humble submission and respect.",
    detailedDef: "Courteous yielding to the judgment, opinion, or will of a revered elder or mentor.",
    example: "In deference to his expertise, the board deferred the final vote until his review.",
    synonyms: ["respect", "regard", "reverence", "esteem"],
    difficulty: "medium",
    category: "Everyday English",
    price: 40
  },
  {
    id: "ebullient",
    word: "Ebullient",
    phonetic: "/ɪˈbʊl.i.ənt/",
    pos: "adjective",
    simpleDef: "Cheerful and full of energy.",
    detailedDef: "Overflowing with bubbling enthusiasm, infectious cheer, and animated exuberance.",
    example: "Her ebullient laughter resonated warmly throughout the festival hall.",
    synonyms: ["exuberant", "buoyant", "joyful", "spirited"],
    difficulty: "medium",
    category: "Emotions",
    price: 45
  },
  {
    id: "facetious",
    word: "Facetious",
    phonetic: "/fəˈsiː.ʃəs/",
    pos: "adjective",
    simpleDef: "Treating serious issues with deliberately inappropriate humor; flippant.",
    detailedDef: "Not meant to be taken seriously; jocose remarks tossed out during grave moments.",
    example: "He made a facetious remark about the rain, but nobody in the soaked line chuckled.",
    synonyms: ["flippant", "jocular", "witty", "ironic"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 65
  },
  {
    id: "germane",
    word: "Germane",
    phonetic: "/dʒɜːˈmeɪn/",
    pos: "adjective",
    simpleDef: "Relevant to a subject under consideration.",
    detailedDef: "Closely and significantly tied to the topic at hand; pertinent and fitting.",
    example: "The judge ruled that the witness's childhood history was not germane to the case.",
    synonyms: ["relevant", "pertinent", "applicable", "apposite"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 65
  },
  {
    id: "iconoclast",
    word: "Iconoclast",
    phonetic: "/aɪˈkɒn.ə.klæst/",
    pos: "noun",
    simpleDef: "A person who attacks cherished beliefs or established traditions.",
    detailedDef: "One who destroys religious images or challenges orthodox revered dogmas.",
    example: "As a musical iconoclast, the composer rejected classical rules to invent new harmonic structures.",
    synonyms: ["rebel", "dissenter", "maverick", "nonconformist"],
    difficulty: "hard",
    category: "Literature",
    price: 70
  },
  {
    id: "judicious",
    word: "Judicious",
    phonetic: "/dʒuːˈdɪʃ.əs/",
    pos: "adjective",
    simpleDef: "Having, showing, or done with good judgment or sense.",
    detailedDef: "Proceeding from wise consideration, balanced discretion, and prudence.",
    example: "Through judicious use of emergency reserves, the city managed the blizzard smoothly.",
    synonyms: ["wise", "sensible", "prudent", "discreet"],
    difficulty: "medium",
    category: "Business",
    price: 40
  },
  {
    id: "labyrinth",
    word: "Labyrinth",
    phonetic: "/ˈlæb.ə.rɪnθ/",
    pos: "noun",
    simpleDef: "A complicated irregular network of passages or paths in which it is difficult to find one's way.",
    detailedDef: "An intricate maze or convoluted entanglement of corridors or bureaucratic procedures.",
    example: "The old castle basement was a confusing labyrinth of arched corridors and vaults.",
    synonyms: ["maze", "network", "web", "snarl"],
    difficulty: "easy",
    category: "Literature",
    price: 25
  },
  {
    id: "magnanimous_dupe",
    word: "Munificent",
    phonetic: "/mjuːˈnɪf.ɪ.sənt/",
    pos: "adjective",
    simpleDef: "Larger or more generous than is usual or necessary.",
    detailedDef: "Exceedingly liberal and lavish in granting gifts, endowments, or donations.",
    example: "The museum expansion was made possible by a munificent bequest from an alumnus.",
    synonyms: ["generous", "bountiful", "lavish", "openhanded"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 70
  },
  {
    id: "nuance",
    word: "Nuance",
    phonetic: "/ˈnjuː.ɑːns/",
    pos: "noun",
    simpleDef: "A subtle difference in or shade of meaning, expression, or sound.",
    detailedDef: "Delicate gradation in tone, color, emotion, or semantic significance.",
    example: "The translator captured every delicate nuance of the poet's original verse.",
    synonyms: ["subtlety", "shade", "refinement", "gradation"],
    difficulty: "easy",
    category: "Literature",
    price: 25
  },
  {
    id: "opulent",
    word: "Opulent",
    phonetic: "/ˈɒp.jə.lənt/",
    pos: "adjective",
    simpleDef: "Ostentatiously rich and luxurious or lavish.",
    detailedDef: "Displaying abundant wealth, sumptuous splendor, and lavish grandeur.",
    example: "The royal palace was decorated in opulent gold leaf and silk tapestry.",
    synonyms: ["luxurious", "sumptuous", "lavish", "palatial"],
    difficulty: "medium",
    category: "Everyday English",
    price: 40
  },
  {
    id: "paradigm",
    word: "Paradigm",
    phonetic: "/ˈpær.ə.daɪm/",
    pos: "noun",
    simpleDef: "A typical example or pattern of something; a model.",
    detailedDef: "A comprehensive philosophical or theoretical framework of scientific concepts.",
    example: "Quantum theory represented a monumental paradigm shift in our view of the universe.",
    synonyms: ["model", "archetype", "framework", "pattern"],
    difficulty: "medium",
    category: "Science",
    price: 45
  },
  {
    id: "resplendent",
    word: "Resplendent",
    phonetic: "/rɪˈsplen.dənt/",
    pos: "adjective",
    simpleDef: "Attractive and impressive through being richly colorful or sumptuous.",
    detailedDef: "Shining brilliantly with dazzling luster and splendor.",
    example: "The peacock displayed its resplendent plumage to admiring spectators.",
    synonyms: ["dazzling", "splendid", "radiant", "glorious"],
    difficulty: "hard",
    category: "Nature",
    price: 65
  },
  {
    id: "scrupulous",
    word: "Scrupulous",
    phonetic: "/ˈskruː.pjə.ləs/",
    pos: "adjective",
    simpleDef: "Diligent, thorough, and extremely attentive to details and moral standards.",
    detailedDef: "Governed by strict integrity; meticulous adherence to exacting rules.",
    example: "The scientist kept scrupulous lab notebooks documenting each temperature fluctuation.",
    synonyms: ["meticulous", "conscientious", "honorable", "exacting"],
    difficulty: "medium",
    category: "Everyday English",
    price: 45
  },
  {
    id: "treacle",
    word: "Truculent",
    phonetic: "/ˈtrʌk.jə.lənt/",
    pos: "adjective",
    simpleDef: "Eager or quick to argue or fight; aggressively defiant.",
    detailedDef: "Cruelly aggressive, belligerent, and combative in temperament.",
    example: "His truculent attitude alienated teammates during what should have been a civil debate.",
    synonyms: ["belligerent", "combative", "aggressive", "hostile"],
    difficulty: "hard",
    category: "Emotions",
    price: 65
  },
  {
    id: "unequivocal",
    word: "Unequivocal",
    phonetic: "/ˌʌn.ɪˈkwɪv.ə.kəl/",
    pos: "adjective",
    simpleDef: "Leaving no doubt; unambiguous.",
    detailedDef: "Expressed with complete certitude; admitting of only one possible interpretation.",
    example: "The committee issued an unequivocal endorsement of the renewable energy initiative.",
    synonyms: ["unambiguous", "unmistakable", "clear-cut", "definite"],
    difficulty: "medium",
    category: "Business",
    price: 45
  },
  {
    id: "veracity",
    word: "Veracity",
    phonetic: "/vəˈræs.ə.ti/",
    pos: "noun",
    simpleDef: "Conformity to facts; accuracy and truthfulness.",
    detailedDef: "Habitual observance of truth and strict precision in statement.",
    example: "The investigator had no reason to doubt the veracity of the eyewitness testimony.",
    synonyms: ["truthfulness", "accuracy", "correctness", "fidelity"],
    difficulty: "medium",
    category: "Advanced Vocabulary",
    price: 40
  },
  {
    id: "whimsical",
    word: "Whimsical",
    phonetic: "/ˈwɪm.zɪ.kəl/",
    pos: "adjective",
    simpleDef: "Playfully quaint or fanciful, especially in an appealing and amusing way.",
    detailedDef: "Determined by chance or eccentric caprice rather than by reason or necessity.",
    example: "The children's book featured whimsical illustrations of flying teacups and singing trees.",
    synonyms: ["fanciful", "playful", "quirky", "eccentric"],
    difficulty: "easy",
    category: "Everyday English",
    price: 20
  },
  {
    id: "zenithal",
    word: "Zephyr",
    phonetic: "/ˈzef.ər/",
    pos: "noun",
    simpleDef: "A soft, gentle breeze.",
    detailedDef: "A light soothing westerly wind bringing refreshing coolness.",
    example: "A fragrant summer zephyr rustled the lavender bushes in the evening.",
    synonyms: ["breeze", "whisper", "draft"],
    difficulty: "medium",
    category: "Nature",
    price: 40
  },
  {
    id: "xenial",
    word: "Xenial",
    phonetic: "/ˈziː.ni.əl/",
    pos: "adjective",
    simpleDef: "Hospitable, warm, and friendly toward guests or strangers.",
    detailedDef: "Pertaining to hospitable warmth between host and guest; welcoming to travelers.",
    example: "The villagers offered a xenial welcome to the tired mountain hikers.",
    synonyms: ["hospitable", "welcoming", "cordial", "gracious"],
    difficulty: "hard",
    category: "Advanced Vocabulary",
    price: 65
  },
  {
    id: "xenon",
    word: "Xenon",
    phonetic: "/ˈzen.ɒn/",
    pos: "noun",
    simpleDef: "A heavy, colorless noble gas that emits a bright blue glow in discharge tubes.",
    detailedDef: "A chemical element of atomic number 54, used in high-intensity lamps and lasers.",
    example: "Modern headlights often utilize xenon gas to generate crisp illumination.",
    synonyms: ["noble gas", "chemical element"],
    difficulty: "medium",
    category: "Science",
    price: 45
  },
  {
    id: "yearn",
    word: "Yearn",
    phonetic: "/jɜːn/",
    pos: "verb",
    simpleDef: "To have an intense, heartfelt longing or desire for something.",
    detailedDef: "To feel deep wistful tenderness or craving for a person, place, or goal.",
    example: "Far from his hometown, he began to yearn for the comforting sound of ocean waves.",
    synonyms: ["long", "pine", "crave", "hanker"],
    difficulty: "easy",
    category: "Emotions",
    price: 25
  },
  {
    id: "yielding",
    word: "Yielding",
    phonetic: "/ˈjiːl.dɪŋ/",
    pos: "adjective",
    simpleDef: "Giving way under pressure; accommodating and flexible.",
    detailedDef: "Characterized by gentle compliance or soft elasticity rather than obstinate resistance.",
    example: "The soft, yielding moss made a comfortable cushion on the forest floor.",
    synonyms: ["flexible", "compliant", "pliable", "accommodating"],
    difficulty: "medium",
    category: "Everyday English",
    price: 35
  }
];

// Starter unlocked word IDs (20 starter words giving immediate coverage across all categories & difficulties)
export const STARTER_WORD_IDS = [
  "abundant",
  "curious",
  "genuine",
  "empathy",
  "serene",
  "blossom",
  "meadow",
  "gravity",
  "molecule",
  "algorithm",
  "bandwidth",
  "budget",
  "revenue",
  "metaphor",
  "prologue",
  "eloquent",
  "kinetic",
  "lucid",       // medium
  "pragmatic",   // medium
  "ubiquitous"   // hard starter so Hard quiz is immediately unlocked!
];
