// Curated Expansion Word Packs for Instant Import
export const EXPANSION_PACKS = {
  gre: [
    {
      id: "anachronism",
      word: "Anachronism",
      phonetic: "/əˈnæk.rə.nɪ.zəm/",
      pos: "noun",
      simpleDef: "A thing belonging or appropriate to a period other than that in which it exists.",
      detailedDef: "Chronological inconsistency in some arrangement, especially a juxtaposition of persons or events from different eras.",
      example: "The presence of a digital wristwatch in the medieval drama was a glaring anachronism.",
      synonyms: ["misplacement", "chronological error", "throwback"],
      difficulty: "hard",
      category: "Literature",
      price: 65
    },
    {
      id: "boisterous",
      word: "Boisterous",
      phonetic: "/ˈbɔɪ.stər.əs/",
      pos: "adjective",
      simpleDef: "Noisy, energetic, and rowdy.",
      detailedDef: "Rough and stormy, or cheerful and unrestrainedly exuberant in demeanor.",
      example: "The boisterous laughter of children echoed across the sunny playground.",
      synonyms: ["lively", "rowdy", "rambunctious", "exuberant"],
      difficulty: "medium",
      category: "Everyday English",
      price: 40
    },
    {
      id: "corroborate",
      word: "Corroborate",
      phonetic: "/kəˈrɒb.ə.reɪt/",
      pos: "verb",
      simpleDef: "To confirm or give support to a statement, theory, or finding.",
      detailedDef: "To make more certain or support with compelling empirical evidence or credible witness testimony.",
      example: "Independent laboratory tests helped corroborate the astrophysicist's daring theory.",
      synonyms: ["confirm", "verify", "substantiate", "validate"],
      difficulty: "medium",
      category: "Science",
      price: 40
    },
    {
      id: "disparate",
      word: "Disparate",
      phonetic: "/ˈdɪs.pər.ət/",
      pos: "adjective",
      simpleDef: "Essentially different in kind; not allowing comparison.",
      detailedDef: "Containing fundamentally distinct or incongruous characteristics that resist unified classification.",
      example: "Scientists synthesized disparate branches of biology and computational mathematics to map the genome.",
      synonyms: ["different", "dissimilar", "distinct", "divergent"],
      difficulty: "hard",
      category: "Advanced Vocabulary",
      price: 65
    },
    {
      id: "equivocate",
      word: "Equivocate",
      phonetic: "/ɪˈkwɪv.ə.keɪt/",
      pos: "verb",
      simpleDef: "To use ambiguous language to conceal the truth or avoid committing oneself.",
      detailedDef: "To deliberately use vague or evasive words with intent to deceive or mislead inquiry.",
      example: "When pressed for financial figures, the executive began to equivocate rather than give clear answers.",
      synonyms: ["prevaricate", "hedge", "evade", "waffle"],
      difficulty: "hard",
      category: "Advanced Vocabulary",
      price: 70
    },
    {
      id: "inchoate",
      word: "Inchoate",
      phonetic: "/ɪnˈkəʊ.eɪt/",
      pos: "adjective",
      simpleDef: "Just begun and so not fully formed or developed; rudimentary.",
      detailedDef: "Existing in an incipient, disordered, or early developmental stage.",
      example: "She organized her inchoate thoughts into a structured and persuasive essay.",
      synonyms: ["rudimentary", "nascent", "embryonic", "unformed"],
      difficulty: "hard",
      category: "Advanced Vocabulary",
      price: 70
    },
    {
      id: "loquacious",
      word: "Loquacious",
      phonetic: "/ləˈkweɪ.ʃəs/",
      pos: "adjective",
      simpleDef: "Tending to talk a great deal; talkative.",
      detailedDef: "Habitually voluble and given to fluent, abundant verbal chatter.",
      example: "The loquacious tour guide shared endless fascinating tales of the ancient cathedral.",
      synonyms: ["talkative", "garrulous", "voluble", "chatty"],
      difficulty: "medium",
      category: "Advanced Vocabulary",
      price: 45
    },
    {
      id: "mendacious",
      word: "Mendacious",
      phonetic: "/menˈdeɪ.ʃəs/",
      pos: "adjective",
      simpleDef: "Not telling the truth; deceitful or lying.",
      detailedDef: "Characterized by habitual deception, falsehood, and dishonesty in speech.",
      example: "The journalist exposed the candidate's mendacious claims about his military credentials.",
      synonyms: ["dishonest", "deceitful", "untruthful", "fallacious"],
      difficulty: "hard",
      category: "Advanced Vocabulary",
      price: 65
    },
    {
      id: "perfunctory",
      word: "Perfunctory",
      phonetic: "/pəˈfʌŋk.tər.i/",
      pos: "adjective",
      simpleDef: "Carried out with a minimum of effort or reflection.",
      detailedDef: "Performed merely as a routine duty without enthusiasm, care, or sincere interest.",
      example: "The inspector gave the machinery only a perfunctory glance before stamping the approval form.",
      synonyms: ["cursory", "hasty", "superficial", "mechanical"],
      difficulty: "hard",
      category: "Advanced Vocabulary",
      price: 65
    },
    {
      id: "sycophant",
      word: "Sycophant",
      phonetic: "/ˈsɪk.ə.fænt/",
      pos: "noun",
      simpleDef: "A person who acts obsequiously toward someone important in order to gain advantage.",
      detailedDef: "A servile, self-seeking flatterer who constantly praises authority for personal advancement.",
      example: "Surrounded by sycophants who never challenged his decrees, the emperor lost touch with reality.",
      synonyms: ["flatterer", "toady", "yes-man", "parasite"],
      difficulty: "hard",
      category: "Advanced Vocabulary",
      price: 70
    },
    {
      id: "vacillate",
      word: "Vacillate",
      phonetic: "/ˈvæs.ɪ.leɪt/",
      pos: "verb",
      simpleDef: "To waver between different opinions or actions; be indecisive.",
      detailedDef: "To swing indecisively from one course of action or conviction to another.",
      example: "He continued to vacillate between accepting the overseas job offer and staying near family.",
      synonyms: ["waver", "hesitate", "oscillate", "dither"],
      difficulty: "medium",
      category: "Emotions",
      price: 45
    },
    {
      id: "zealot",
      word: "Zealot",
      phonetic: "/ˈzel.ət/",
      pos: "noun",
      simpleDef: "A person who is fanatical and uncompromising in pursuit of their religious or political ideals.",
      detailedDef: "An excessively enthusiastic and uncompromising partisan devoted to a singular cause.",
      example: "The reform zealot championed strict environmental conservation without any compromise.",
      synonyms: ["fanatic", "enthusiast", "partisan", "extremist"],
      difficulty: "medium",
      category: "Advanced Vocabulary",
      price: 40
    }
  ],

  science: [
    {
      id: "cybernetics",
      word: "Cybernetics",
      phonetic: "/ˌsaɪ.bəˈnet.ɪks/",
      pos: "noun",
      simpleDef: "The science of communications and automatic control systems in machines and living things.",
      detailedDef: "Comparative study of regulatory, computational, and feedback systems in biology and technology.",
      example: "Early research into cybernetics laid the foundation for modern autonomous robotic feedback loops.",
      synonyms: ["automation", "control systems", "robotics"],
      difficulty: "hard",
      category: "Science",
      price: 65
    },
    {
      id: "distributed",
      word: "Distributed",
      phonetic: "/dɪˈstrɪb.jʊ.tɪd/",
      pos: "adjective",
      simpleDef: "Shared among or spread out over multiple computers or nodes in a network.",
      detailedDef: "Operating across coordinated decentralized autonomous systems rather than a single server.",
      example: "The blockchain operates as an immutable distributed ledger maintained by nodes globally.",
      synonyms: ["decentralized", "dispersed", "networked"],
      difficulty: "medium",
      category: "Technology",
      price: 40
    },
    {
      id: "scalability",
      word: "Scalability",
      phonetic: "/ˌskeɪ.ləˈbɪl.ə.ti/",
      pos: "noun",
      simpleDef: "The capacity of a system to grow and handle increasing amounts of work smoothly.",
      detailedDef: "The ability of software architectures to preserve performance when transaction volume multiplies.",
      example: "Engineers redesigned the cloud database to guarantee scalability during peak holiday shopping.",
      synonyms: ["expandability", "adaptability", "growth potential"],
      difficulty: "easy",
      category: "Technology",
      price: 25
    },
    {
      id: "interface",
      word: "Interface",
      phonetic: "/ˈɪn.tə.feɪs/",
      pos: "noun",
      simpleDef: "A point where two systems, subjects, or organizations meet and interact.",
      detailedDef: "A shared boundary across which components exchange data and interactive signals.",
      example: "The intuitive graphical user interface allowed novice users to edit videos with ease.",
      synonyms: ["connection", "boundary", "junction", "portal"],
      difficulty: "easy",
      category: "Technology",
      price: 20
    },
    {
      id: "virtualization",
      word: "Virtualization",
      phonetic: "/ˌvɜː.tʃu.ə.laɪˈzeɪ.ʃən/",
      pos: "noun",
      simpleDef: "The creation of a virtual rather than actual version of something, such as an operating system.",
      detailedDef: "Software abstraction allowing multiple independent logical OS instances on single hardware.",
      example: "Server virtualization slashed energy consumption and hardware footprint across the datacenter.",
      synonyms: ["emulation", "abstraction", "cloud computing"],
      difficulty: "hard",
      category: "Technology",
      price: 65
    },
    {
      id: "kismet",
      word: "Kismet",
      phonetic: "/ˈkɪz.met/",
      pos: "noun",
      simpleDef: "Destiny or fate.",
      detailedDef: "The predetermined decree of providence; a serendipitous occurrence ordained by fate.",
      example: "Meeting her future research partner on a delayed cross-country flight felt like pure kismet.",
      synonyms: ["fate", "destiny", "fortune", "providence"],
      difficulty: "medium",
      category: "Everyday English",
      price: 40
    }
  ],

  literature: [
    {
      id: "bucolic",
      word: "Bucolic",
      phonetic: "/bjuːˈkɒl.ɪk/",
      pos: "adjective",
      simpleDef: "Relating to the pleasant aspects of the countryside and country life.",
      detailedDef: "Charming, pastoral, and idyllically rustic; celebrating agrarian simplicity.",
      example: "The artist painted a bucolic landscape of grazing sheep beneath rolling hills.",
      synonyms: ["pastoral", "rustic", "rural", "country"],
      difficulty: "medium",
      category: "Literature",
      price: 45
    },
    {
      id: "chimerical",
      word: "Chimerical",
      phonetic: "/kaɪˈmer.ɪ.kəl/",
      pos: "adjective",
      simpleDef: "Existing only as the product of unchecked imagination; fantastically visionary or improbable.",
      detailedDef: "Unrealistically fanciful, mythical, or wildly illusory in nature.",
      example: "The alchemist's chimerical dream of turning lead into gold consumed his fortune.",
      synonyms: ["fanciful", "illusory", "mythical", "visionary"],
      difficulty: "hard",
      category: "Literature",
      price: 70
    },
    {
      id: "diaphanous",
      word: "Diaphanous",
      phonetic: "/daɪˈæf.ən.əs/",
      pos: "adjective",
      simpleDef: "Light, delicate, and translucent.",
      detailedDef: "Possessing airy delicacy of texture permitting light to filter softly through.",
      example: "The ballerina floated across the stage in a diaphanous silk gown that shimmered under spotlights.",
      synonyms: ["sheer", "translucent", "delicate", "gauzy"],
      difficulty: "hard",
      category: "Literature",
      price: 65
    },
    {
      id: "effervescent",
      word: "Effervescent",
      phonetic: "/ˌef.əˈves.ənt/",
      pos: "adjective",
      simpleDef: "Giving off bubbles, or vivacious and enthusiastic.",
      detailedDef: "Bubbling with sparkling vitality, high spirits, and infectious buoyant joy.",
      example: "Her effervescent personality lit up the room the moment she arrived.",
      synonyms: ["sparkling", "bubbly", "vivacious", "ebullient"],
      difficulty: "medium",
      category: "Everyday English",
      price: 40
    },
    {
      id: "wistful",
      word: "Wistful",
      phonetic: "/ˈwɪst.fəl/",
      pos: "adjective",
      simpleDef: "Having or showing a feeling of vague or regretful longing.",
      detailedDef: "Penetrated with contemplative nostalgia, melancholy yearning, and quiet desire.",
      example: "He cast a wistful glance at the departing train that carried his childhood companions.",
      synonyms: ["nostalgic", "yearning", "longing", "pensive"],
      difficulty: "easy",
      category: "Emotions",
      price: 25
    }
  ]
};
